# .travis.yml
# When a tagged commit is pushed the documentation pages and npm module are published/deployed:
# npm version patch -m "%s Release"
language: node_js
node_js:
  - "10"
branches:
  only:
    - master
    - "/v*/"
script:
# - printenv
  - "npm test"
# Using before_deploy will run before every deploy resulting in running multiple times when there is
# one or more deploy providers and will run regardless of the "on" directive used on the desired
# provider. Instead, a single script provider handles any pre-deployment executions.
#before_deploy:
#  - "npm run jspub"
before_deploy:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
deploy:
# Using the pages provider will wipe out previously deployed pages for prior versions. This makes it
# difficult to navigate version history and link to via documentation.
#  - provider: pages
#    skip-cleanup: true
#    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#    keep-history: true
#    target-branch: gh-pages
#    local-dir: docs
#    on:
#      tags: true # only on tagging commit
#      all_branches: true
  - provider: script
    skip_cleanup: true
    script: npm run jspub-deploy
    on:
      tags: true # only on tagging commit
      branch:
        - /v(\d+\.)?(\d+\.)?(\*|\d+)$/
  - provider: npm
    email: "ugate.public@gmail.com"
    api_key: $NPM_TOKEN  # Set in the settings page of your repository, as a secure variable
    on:
      tags: true # only on tagging commit
      branch:
        - /v(\d+\.)?(\d+\.)?(\*|\d+)$/